# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules:
  - identifier_name
  - todo
  - type_name
  - cyclomatic_complexity
  - trailing_comma
  - redundant_optional_initialization

opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - array_init
  - balanced_xctest_lifecycle
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
#  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
#  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_subject
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - sorted_first_last
  - static_operator
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unavailable_function
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

analyzer_rules:
  - unused_declaration
  - unused_import

force_cast: warning
force_try: warning
line_length:
  warning: 120
  error: 240
  ignores_comments: true
function_body_length:
  warning: 60
type_body_length: [200, 400]

trailing_whitespace:
  ignores_empty_lines: true

unused_declaration:
  include_public_and_open: true

#type_contents_order:
#  order:
#    - case
#    - type_alias
#    - associated_type
#    - type_property
#    - instance_property
#    - ib_inspectable
#    - ib_outlet
#    - initializer
#    - type_method
#    - view_life_cycle_method
#    - ib_action
#    - other_method
#    - subscript
#    - deinitializer
#    - subtype
multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true
modifier_order:
  preferred_modifier_order:
    - override
    - acl
    - setterACL
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
