disabled_rules:
  - implicitly_unwrapped_optional
  - line_length
  - multiline_arguments_brackets
  - multiline_arguments
  - force_try
  - function_body_length
  - multiline_function_chains
  - inclusive_language
  - function_parameter_count
