# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "AppStore Screenshots")
    # Only upload the screenshots
    :deliverScreenshots
  end
  
  lane :deployScreenshots do
    upload_to_app_store(
    	skip_binary_upload: true,
    	skip_metadata: true,
    	skip_app_version_update: true,
    	overwrite_screenshots: true
    )
  end
end